
export const DELAY_SET  = 'DELAY_SET';

export const FIELD_CHANGED  = 'FIELD_CHANGED';
export const FIELD_LINES_RESOLVED  = 'FIELD_LINES_RESOLVED';
export const FIELD_NOT_CHANGED  = 'FIELD_NOT_CHANGED';

export const GAME_INIT  = 'GAME_INIT';
export const GAME_NEXT  = 'GAME_NEXT';
export const GAME_OVER  = 'GAME_OVER';
export const GAME_PAUSE  = 'GAME_PAUSE';
export const GAME_PAUSED  = 'GAME_PAUSED';
export const GAME_START  = 'GAME_START';
export const GAME_COUNT_DOWN = 'GAME_COUNT_DOWN';
export const GAME_ASCII_SWITCH  = 'GAME_ASCII_SWITCH';

export const STONE_CREATE  = 'STONE_CREATE';
export const STONE_INSERT  = 'STONE_INSERT';
export const STONE_INSERTED  = 'STONE_INSERTED';
export const STONE_INSERT_REJECT  = 'STONE_INSERT_REJECT';
export const STONE_MOVE_DOWN  = 'STONE_MOVE_DOWN';
export const STONE_MOVED_DOWN  = 'STONE_MOVED_DOWN';
export const STONE_MOVE_DOWN_REJECTED  = 'STONE_MOVE_DOWN_REJECTED';
export const STONE_PULL_DOWN  = 'STONE_PULL_DOWN';
export const STONE_PULLED_DOWN  = 'STONE_PULLED_DOWN';
export const STONE_ROTATE  = 'STONE_ROTATE';
export const STONE_ROTATED  = 'STONE_ROTATED';
export const STONE_ROTATE_REJECTED  = 'STONE_ROTATE_REJECTED';
export const STONE_MOVE_LEFT  = 'STONE_MOVE_LEFT';
export const STONE_MOVED_LEFT  = 'STONE_MOVED_LEFT';
export const STONE_MOVE_LEFT_REJECTED  = 'STONE_MOVE_LEFT_REJECTED';
export const STONE_MOVE_RIGHT  = 'STONE_MOVE_RIGHT';
export const STONE_MOVED_RIGHT  = 'STONE_MOVED_RIGHT';
export const STONE_MOVE_RIGHT_REJECTED  = 'STONE_MOVE_RIGHT_REJECTED';

export const AUTH_JOIN = 'AUTH_JOIN';
export const AUTH_JOINED = 'AUTH_JOINED';
export const AUTH_LEAVE = 'AUTH_LEAVE';
export const AUTH_UID_RECEIVED = 'AUTH_UID_RECEIVED';
export const SERVER_AUTH_JOIN = 'SERVER_AUTH_JOIN';

export const CHAT_OPEN = 'CHAT_OPEN';
export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
export const CHAT_MESSAGE_SEND = 'CHAT_MESSAGE_SEND';
export const CHAT_WINDOW_CLOSE = 'CHAT_WINDOW_CLOSE';
export const CHAT_WINDOW_FOCUS = 'CHAT_WINDOW_FOCUS';
export const CHAT_WINDOW_OPEN = 'CHAT_WINDOW_OPEN';
export const SERVER_CHAT_OPEN = 'SERVER_CHAT_OPEN';
export const SERVER_CHAT_MESSAGE = 'SERVER_CHAT_MESSAGE';

export const MULTIPLAY_ACCEPT = 'MULTIPLAY_ACCEPT';
export const MULTIPLAY_CANCEL = 'MULTIPLAY_CANCEL';
export const MULTIPLAY_CANCELED = 'MULTIPLAY_CANCELED';
export const MULTIPLAY_INVITE = 'MULTIPLAY_INVITE';
export const MULTIPLAY_INVITATION = 'MULTIPLAY_INVITATION';
export const MULTIPLAY_START = 'MULTIPLAY_START';
export const SERVER_MULTIPLAY_ACCEPT = 'SERVER_MULTIPLAY_ACCEPT';
export const SERVER_MULTIPLAY_CANCEL = 'SERVER_MULTIPLAY_CANCEL';
export const SERVER_MULTIPLAY_INVITE = 'SERVER_MULTIPLAY_INVITE';

export const ONLINE_JOIN = 'ONLINE_JOIN';
export const ONLINE_LEAVE = 'ONLINE_LEAVE';
export const SERVER_ONLINE_JOIN = 'SERVER_ONLINE_JOIN';
export const SERVER_ONLINE_LEAVE = 'SERVER_ONLINE_LEAVE';

export const SERVER_CXN = 'SERVER_CXN';
export const SERVER_DXN = 'SERVER_DXN';

export const WEBSOCKET_ERROR = 'WEBSOCKET_ERROR';
export const WINDOW_RESTORE_SLAVE  = 'WINDOW_RESTORE_SLAVE';
