
export const DELAY_SET  = 'DELAY_SET';

export const FIELD_CHANGED  = 'FIELD_CHANGED';
export const FIELD_LINES_RESOLVED  = 'FIELD_LINES_RESOLVED';
export const FIELD_NOT_CHANGED  = 'FIELD_NOT_CHANGED';

export const GAME_INIT  = 'GAME_INIT';
export const GAME_NEXT  = 'GAME_NEXT';
export const GAME_OVER  = 'GAME_OVER';
export const GAME_PAUSE  = 'GAME_PAUSE';
export const GAME_PAUSED  = 'GAME_PAUSED';
export const GAME_START  = 'GAME_START';
export const GAME_COUNT_DOWN = 'GAME_COUNT_DOWN';
export const GAME_ASCII_SWITCH  = 'GAME_ASCII_SWITCH';

export const STONE_CREATE  = 'STONE_CREATE';
export const STONE_INSERT  = 'STONE_INSERT';
export const STONE_INSERTED  = 'STONE_INSERTED';
export const STONE_INSERT_REJECT  = 'STONE_INSERT_REJECT';
export const STONE_MOVE_DOWN  = 'STONE_MOVE_DOWN';
export const STONE_MOVED_DOWN  = 'STONE_MOVED_DOWN';
export const STONE_MOVE_DOWN_REJECTED  = 'STONE_MOVE_DOWN_REJECTED';
export const STONE_PULL_DOWN  = 'STONE_PULL_DOWN';
export const STONE_PULLED_DOWN  = 'STONE_PULLED_DOWN';
export const STONE_ROTATE  = 'STONE_ROTATE';
export const STONE_ROTATED  = 'STONE_ROTATED';
export const STONE_ROTATE_REJECTED  = 'STONE_ROTATE_REJECTED';
export const STONE_MOVE_LEFT  = 'STONE_MOVE_LEFT';
export const STONE_MOVED_LEFT  = 'STONE_MOVED_LEFT';
export const STONE_MOVE_LEFT_REJECTED  = 'STONE_MOVE_LEFT_REJECTED';
export const STONE_MOVE_RIGHT  = 'STONE_MOVE_RIGHT';
export const STONE_MOVED_RIGHT  = 'STONE_MOVED_RIGHT';
export const STONE_MOVE_RIGHT_REJECTED  = 'STONE_MOVE_RIGHT_REJECTED';

export const WINDOW_RESTORE_SLAVE  = 'WINDOW_RESTORE_SLAVE';
